# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# create roles
r1 = Role.create({name: "Regular", description: "Can read items"})
r2 = Role.create({name: "Seller", description: "Can read and create items. Can update and destroy own items"})
r3 = Role.create({name: "Admin", description: "Can perform any CRUD operation on any resource"})
# create a master admin account for starting use of the site
u1 = User.create({name: "Don", email: "Don@bahamallama.com", password: "aaaaaaaa", password_confirmation: "aaaaaaaa", role_id: r3.id})
# create Makes of Cars
m1 = Make.create({name: "Acura"})
m2 = Make.create({name: "Alfa Romero"})
m3 = Make.create({name: "Aston Martin"})
m4 = Make.create({name: "Audi"})
m5 = Make.create({name: "Bentley"})
m6 = Make.create({name: "BMW"})
m7 = Make.create({name: "Buick"})
m8 = Make.create({name: "Cadillac"})
m9 = Make.create({name: "Chevrolet"})
m10 = Make.create({name: "Chrysler"})
m11 = Make.create({name: "Dodge"})
m12 = Make.create({name: "Ferrari"})
m13 = Make.create({name: "Fiat"})
m14 = Make.create({name: "Ford"})
m15 = Make.create({name: "GMC"})
m16 = Make.create({name: "Honda"})
m17 = Make.create({name: "Hyundai"})
m18 = Make.create({name: "Infiniti"})
m19 = Make.create({name: "Jaguar"})
m20 = Make.create({name: "Jeep"})
m21 = Make.create({name: "Kia"})
m22 = Make.create({name: "Lamborghini"})
m23 = Make.create({name: "Land Rover"})
m24 = Make.create({name: "Lexus"})
m25 = Make.create({name: "Lincoln"})
m26 = Make.create({name: "Lotus"})
m27 = Make.create({name: "Maserati"})
m28 = Make.create({name: "Mazda"})
m29 = Make.create({name: "McLaren"})
m30 = Make.create({name: "Mercedes Benz"})
m31 = Make.create({name: "Mini"})
m32 = Make.create({name: "Mitsubishi"})
m33 = Make.create({name: "Nissan"})
m34 = Make.create({name: "Porsche"})
m35 = Make.create({name: "Ram"})
m36 = Make.create({name: "Rolls Royce"})
m37 = Make.create({name: "Scion"})
m38 = Make.create({name: "Smart"})
m39 = Make.create({name: "Subaru"})
m40 = Make.create({name: "Tesla"})
m41 = Make.create({name: "Toyota"})
m42 = Make.create({name: "Volkswagen"})
m43 = Make.create({name: "Volvo"})
